// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbczaumjqcctsxbheejf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiY3phdW1qcWNjdHN4YmhlZWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDI1OTksImV4cCI6MjA2NjUxODU5OX0.AxnWZLnRPJQ7KXY20lfeCJ4QT4xZNRGTB2Rg5Ctae8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});