// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aomisprfxjatoibvcmhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbWlzcHJmeGphdG9pYnZjbWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjEwMzAsImV4cCI6MjA3MDIzNzAzMH0.8rp5hX1Hj2UgcIgijf3YJ5A30GJW_l3yRcLfO6hiURw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});